
rabbitmq:
  clusterEnabled: "false"
  connstr: "rabbitmq://user:{0}@rabbitmq-helm.tst01-identifeye.svc.cluster.local:5672"
  useSSL: "false"
  user: "user"
  host: rabbitmq-helm.tst01-identifeye.svc.cluster.local

redis:
  useSentienl: "true"
  sentinelHosts: redis-helm.tst01-identifeye.svc.cluster.local:26379
  useSSL: "false"
  
vault:
  clusterEnabled: "false"
  path: "http://vault-ha-helm.tst01-identifeye.svc.cluster.local:8200"
  secret: "NOSECRET"
  role: "9d544af4-c4d5-25a0-50d2-190a6ae49b08"
    
consul:
  path: "http://consul-viki-server.tst01-identifeye.svc.cluster.local:8500"

elastic:
  enabled: "true"
  uri: "http://elasticsearch-master.monitoring.svc.cluster.local:9200"

sts:
  baseAddress: "http://stsapi.default.svc.cluster.local:8081"

splunk:
  runSplunk: "false"

kafka: 
  enabled: "false"
