apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: map-demo
  name: map-demo 
spec:
  type: ClusterIP
  ports:
    - name: "http" 
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: map-demo
