apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: multifacebioapi
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: multifacebioapi
  template:
    metadata:
      labels:
        io.kompose.network/prod: "true"
        io.kompose.service: multifacebioapi
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          image: quay.io/vikisense/vikisql:mfb
          imagePullPolicy: Always
          # livenessProbe:
          #   exec:
          #     command:
          #       - wget --no-verbose --tries=1 http://localhost:446/api/health/live || exit 1
          #   failureThreshold: 3
          #   initialDelaySeconds: 10
          #   periodSeconds: 30
          #   timeoutSeconds: 5
          name: multifacebioapi
          ports:
            - containerPort: 500
              protocol: TCP
      imagePullSecrets:
        - name: vikisense-vikiclalit-pull-secret
      restartPolicy: Always
