apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  RabbitMq__ClusterEnabled: "{{ .Values.rabbitmq.clusterEnabled }}"
  RabbitMq__ConnStr: "{{ .Values.rabbitmq.connstr }}"
  RabbitMq__UseSsl: "{{ .Values.rabbitmq.useSSL }}"
  RabbitMq__User: "{{ .Values.rabbitmq.user }}"
  RabbitMq__Host: {{ .Values.rabbitmq.host }}
  Redis__UseSentienl: "{{ .Values.redis.useSentienl }}"
  Redis__SentinelHosts: {{ .Values.redis.sentinelHosts }}
  Redis__UseSSl: "{{ .Values.redis.useSSL }}"
  ASPNETCORE__ENVIRONMENT: "{{ .Values.aspnetcore.environment }}"
  FaceEngineSettings__MatchThreshold: "{{ .Values.faceEngine.matchThreshold }}"
  FaceEngineSettings__LiveThreshold: "{{ .Values.faceEngine.liveThreshold }}"
  FaceEngineSettings__BlurThreshold: "{{ .Values.faceEngine.blurThreshold }}"
  FaceEngineSettings__CheckBlur: "{{ .Values.faceEngine.checkBlur }}"
  FaceEngineSettings__LogResult: "{{ .Values.faceEngine.logResult }}"
  FaceEngineSettings__RunOneToMany: "{{ .Values.faceEngine.runOnetoMany }}"
  API__IgnoreEngine: "{{ .Values.api.ignoreEngine }}"
  ElasticConfiguration__Uri: "{{ .Values.elastic.uri }}"
