apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: voice
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: voice
  template:
    metadata:
      labels:
        io.kompose.network/prod: "true"
        io.kompose.service: voice
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          image: quay.io/vikisense/vikisql:core-voice-sql1
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - wget --no-verbose --tries=1 http://localhost:449/api/health/live || exit 1
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          name: voice
          ports:
            - containerPort: 449
              protocol: TCP
      imagePullSecrets:
        - name: vikisense-vikiclalit-pull-secret
      restartPolicy: Always
