apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: voice
  name: voice 
spec:
  ports:
    - name: "449" 
      port: 80
      targetPort: 449
  selector:
    io.kompose.service: voice
