apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mapapi
  name: mapapi 
spec:
  ports:
    - name: "447" 
      port: 80
      targetPort: 447
  selector:
    io.kompose.service: mapapi
