apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: core
  name: core 
spec:
  ports:
    - name: "446" 
      port: 80
      targetPort: 446
  selector:
    io.kompose.service: core
