apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.CoreconfigMap.name }}
data:
  RabbitMq__ClusterEnabled: "{{ .Values.rabbitmq.clusterEnabled }}"
  RabbitMq__ConnStr: "{{ .Values.rabbitmq.connstr }}"
  RabbitMq__UseSsl: "{{ .Values.rabbitmq.useSSL }}"
  RabbitMq__User: "{{ .Values.rabbitmq.user }}"
  RabbitMq__Host: {{ .Values.rabbitmq.host }}
  Redis__UseSentienl: "{{ .Values.redis.useSentienl }}"
  Redis__SentinelHostsComma: {{ .Values.redis.sentinelHosts }}
  Redis__UseSSl: "{{ .Values.redis.useSSL }}"
  VaultConfig__ClusterEnabled: "{{ .Values.vault.clusterEnabled }}"
  VaultConfig__Path: "{{ .Values.vault.path }}"
  ConsulConfig__Path: "{{ .Values.consul.path }}"
  vault_default_secret: "{{ .Values.vault.secret }}"
  vault_core_role: "{{ .Values.vault.role }}"
  ElasticConfiguration__Enabled: "{{ .Values.elastic.enabled }}"
  ElasticConfiguration__Uri: "{{ .Values.elastic.uri }}"
  Db__Type: "{{ .Values.db.type }}"
