apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: map-demo
  name: {{ .Values.Demodeployment.name }}
spec:
  replicas: {{ .Values.Demodeployment.replicas }}
  selector:
    matchLabels:
      io.kompose.service: map-demo
  template:
    metadata:
      labels:
        io.kompose.network/prod: "true"
        io.kompose.service: map-demo
    spec:
      containers:
        - image: {{ .Values.Demodeployment.image }}
          name: map-demo
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      restartPolicy: Always
