apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: face
  name: {{ .Values.Facedeployment.name }}
spec:
  replicas: {{ .Values.Facedeployment.replicas }}
  selector:
    matchLabels:
      io.kompose.service: face
  template:
    metadata:
      labels:
        io.kompose.network/prod: "true"
        io.kompose.service: face
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: {{ .Values.FaceconfigMap.name }}
          image: {{ .Values.Facedeployment.image }}
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - wget --no-verbose --tries=1 http://localhost:448/api/health/live || exit 1
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          name: face
          ports:
            - containerPort: 448
              protocol: TCP
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      restartPolicy: Always
