apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: multifacebioapi
  name: multifacebioapi 
spec:
  ports:
    - name: "8086" 
      port: 8086
      targetPort: 500
  selector:
    io.kompose.service: multifacebioapi
