apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: multifacebioapi
  name: {{ .Values.Mfbdeployment.name }}
spec:
  replicas: {{ .Values.Mfbdeployment.replicas }}
  selector:
    matchLabels:
      io.kompose.service: multifacebioapi
  template:
    metadata:
      labels:
        io.kompose.network/prod: "true"
        io.kompose.service: multifacebioapi
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: {{ .Values.MfbconfigMap.name }}
          image: {{ .Values.Mfbdeployment.image }}
          imagePullPolicy: Always
          # livenessProbe:
          #   exec:
          #     command:
          #       - wget --no-verbose --tries=1 http://localhost:446/api/health/live || exit 1
          #   failureThreshold: 3
          #   initialDelaySeconds: 10
          #   periodSeconds: 30
          #   timeoutSeconds: 5
          name: multifacebioapi
          ports:
            - containerPort: 500
              protocol: TCP
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      restartPolicy: Always
