apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: face
  name: face 
spec:
  ports:
    - name: "448" 
      port: 80
      targetPort: 448
  selector:
    io.kompose.service: face
